### ISSUE TITLE
DELL G5 5511 Driver Not Found

### ISSUE THREAD

**Issue by RaR1991** [T-Troll/alienfan-tools#28]
Hello I'm getting driver not found on dell g15 5511 intel 11800h 

this is a link for acpi dump

[link removed]

**Comment by T-Troll** [comment]
Do you mean "Driver did not start or supported hardware not detected" from `alienfan-gui`?

First, check it's not antivirus issue (some of them don't like driver loaded) - you should have `hwacc.sys`, `kdl.dll` and `drv64.dll` into the same folder with `alienfan-gui`.

If this not AV issue, let me check. Thanks for dump, but i have it already from the other guy. I check it anyway (maybe it's new BIOS issue),

**Comment by T-Troll** [comment]
Yes, they change BIOS as well (quite good design now, by the way).
Please check this version - it can fix detection - [alienfan-gui.zip](https://github.com/T-Troll/alienfan-tools/files/7786958/alienfan-gui.zip)
Unpack it into the same folder as before, overwriting the old one.

**Comment by RaR1991** [comment]
thank you

**Comment by T-Troll** [comment]
Looks crazy for me. Wrong temperature sensor detection? But they are numbered the same way into BIOS.
Looks like Indian code, nothing else.
