### ISSUE TITLE
kernel_security_check_failure bsod when trying to use fan control

### ISSUE THREAD

**Issue by t0asts** [T-Troll/alienfan-tools#31]
model: area 51 r4 i9-7900x

event viewer log:
The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000139 (0x0000000000000006, 0xffffef81fc5fea40, 0xffffef81fc5fe998, 0x0000000000000000). A dump was saved in: C:\WINDOWS\MEMORY.DMP. Report Id: 991817f7-7b6c-4496-8cdd-be0863f931a7.

**Comment by T-Troll** [comment]
In fact, we have 2 issues in one here.

One is BSOD. It's nice to have minidump, but i see right now it's you antivirus-related. It's strange, seems like Microsoft update antivirus to handle this situation (i need to load unsigned kernel driver).
For check, try this:
- Disable anitvirus. Try to run app.
- If still BSOD, go to BIOS and disable "Secure boot", and then anitvirus.
- If both didn't help, i need to check about this situation deeper.

Second one is you BIOS not supported now (and it's hilarious one, never see something like this).
One side, it (potentially) have functions i need, but they put 1-second delay every call (for what?), another side i don't sure it's not a fake (like GPU power modes on some systems).
So i'll provide you a test version to check tomorrow (in case we are fixed the first issue).

**Comment by t0asts** [comment]
secure boot is disabled, all av is disabled no usermode hooks or kernelmode callbacks, and i am able to run kdu to load drivers without issue, but am happy to provide mindidump ill pm you on discord with it

**Comment by T-Troll** [comment]
So KDU is loaded, but my driver still BSODed?

**Comment by t0asts** [comment]
yes kdu is able to load a test driver.

**Comment by T-Troll** [comment]
Hmm... We have a bug before about BSOD at driver _unload_... Seems like it come back.
Ok, thanks, let me check.

**Comment by T-Troll** [comment]
Fixed in [1.7.0](https://github.com/T-Troll/alienfan-tools/releases/tag/1.7.0).

Please check and close issue if work correctly.
